spring.application.name=device-service
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:2222/home_energy_tracker
spring.datasource.username=homeEnergyUser
spring.datasource.password=homeEnergyPassword

# Controls DDL auto-generation (keep as false/none, or update to validate, create-drop, etc.)
spring.jpa.hibernate.ddl-auto=none